-- MySQL Script generated by MySQL Workbench
-- 02/13/17 19:41:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBestudiantes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBestudiantes` ;

-- -----------------------------------------------------
-- Schema DBestudiantes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBestudiantes` DEFAULT CHARACTER SET utf8 ;
USE `DBestudiantes` ;

-- -----------------------------------------------------
-- Table `DBestudiantes`.`TEstudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBestudiantes`.`TEstudiantes` ;

CREATE TABLE IF NOT EXISTS `DBestudiantes`.`TEstudiantes` (
  `No` INT AUTO_INCREMENT NOT NULL,
  `Matricula` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Seccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`No`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
